# Generated by Django 3.1 on 2020-09-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200822_0939"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="requested_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("data prepper", "Data Prepper"),
                    ("OFA analyst", "Ofa Analyst"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("data prepper", "Data Prepper"),
                    ("OFA analyst", "Ofa Analyst"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="STT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("state", "State"),
                            ("territory", "Territory"),
                            ("tribe", "Tribe"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("name", models.CharField(max_length=1000)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stts",
                        to="users.region",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.stt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="stt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.stt",
            ),
        ),
    ]
