# Generated by Django 3.1 on 2020-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200902_1847'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stt',
            constraint=models.UniqueConstraint(fields=('name',), name='stt_uniq_name'),
        ),
    ]
